export * from './page.component';
export * from './login/login.component';
export * from './register/register.component';
export * from './landing/landing.component';
export * from './password-recovery/password-recovery.component';
export * from './post-sale/post-sale.component';
export * from './privacy/privacy.component';
export * from './terms-of-service/terms-of-service.component';
export * from './contact/contact.component';
