export * from './admin.component';
export * from './establishment/establishment.component';
export * from './category/category.component';
export * from './product/product.component';
export * from './product/product-list/product-list.component';
export * from './product/product-register/product-register.component';
export * from './price-layer/price-layer.component';
export * from './config/config.component';
export * from './address/address.component';
